### ISSUE TITLE
Phase 0 - Cars move 2x per iteration when stopping

### ISSUE THREAD

**Issue by camhart** [camhart/ultimatetraffic#11]
In phase 0, cars are moving 2x per iteration.

Using the first 20 cars of the new cars.csv file (Brian just updated it).  Set GUI to start at iteration 521.  Change the Time per iteration to 1.0 so it slows the gui down.  Click run, then pause it really fast.  Write down the position of any car approaching a red light (Car id 10 should be at position 506.0).  Now unpause then pause again (only let 1 iteration pass).  Now check that same cars position.  It will have moved 2 times during the single iteration (Car id 10 ends up at position 510.4).

Car 10 moved 4.4 meters in 0.1 ms.  Thats 2x the cars velocity which is 22m/s (or 2.2 meters moved per iteration).  Somehow the car is being moved forward twice.

**Comment by camhart** [comment]
Josh fixed this but as a result a new bug occurred where cars are no longer stopping in their proper positions.  The cars themselves are given correct stopping positions.

![Image of simulator](http://oi58.tinypic.com/2gy61qr.jpg)

http://pastebin.com/bmM4h4Ah

**Comment by camhart** [comment]
The velocity of the cars stopping in wrong positions stays at 22 m/s for some weird reason.

**Comment by camhart** [comment]
Fixed by josh https://github.com/camhart/ultimatetraffic/commit/3d785b491201887b3c9bac9667ad956e9ad0bd2b

**Comment by urrry1** [comment]
Running with phase 0 lights, the bug is still quite prevalent... Running with phase 1 lights, it appears to be omnipresent--ALL cars are moving twice as fast as they should. A quick distance divided by speed shows that cars are going way faster than 22 m/s.

**Comment by urrry1** [comment]
Looks like I cried wolf on this one by accident. For some reason git was telling me it had successfully pulled the new code when it hadn't. No bugs here...
